// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'trip_students_model.mapper.dart';

@MappableClass()
class TripStudentsModel with TripStudentsModelMappable {
  final String? id;
  //student_id
  @MappableField(key: 'trip_id')
  final String tripId;
  @MappableField(key: 'student_id')
  final String studentId;
  @MappableField(key: 'pickup_status')
  final String pickupStatus;
  @MappableField(key: 'dropoff_status')
  final String dropoffStatus;
  @MappableField(key: 'pickup_time')
  final DateTime? pickupTime;
  @MappableField(key: 'dropoff_time')
  final DateTime? dropoffTime;

  TripStudentsModel({
   required this.pickupStatus,required this.dropoffStatus, 
    required this.id,
    required this.tripId,
    required this.studentId,
    required this.dropoffTime,
    this.pickupTime,
  });
}
