name: my_little_route
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  supabase_flutter: ^2.9.1
  easy_localization: ^3.0.7+1
  intl: ^0.20.2
  flutter_dotenv: ^5.2.1
  dart_mappable: ^4.5.0
  get_it: ^8.0.3
  shared_preferences: ^2.5.3
  http: ^1.4.0
  flutter_svg: ^2.2.0
  fade_shimmer: ^2.4.0
  flutter_native_splash: ^2.4.6 # تأكد من وجودها هنا
  image_picker: ^1.1.2
  # google_fonts: ^6.2.1
  flutter_launcher_icons: ^0.14.4
  geocoding: ^4.0.0
  google_maps_flutter: ^2.12.3
  geolocator: ^14.0.2
  flutter_polyline_points: ^3.0.1
  location: ^8.0.1
  

dev_dependencies: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.6
  build_runner: 2.5.4
  dart_mappable_builder: ^4.5.0 
 
flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/translations/
   
    - assets/image/
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
        - asset: assets/fonts/Cairo-Light.ttf
        - asset: assets/fonts/Cairo-Medium.ttf

    - family: SFCompactRounded
      fonts:
        - asset: assets/fonts/SF-Compact-Rounded-Regular.otf
          weight: 400
        - asset: assets/fonts/SF-Compact-Rounded-Bold.otf
          weight: 700
 
flutter_native_splash:
  color: "#ffffff"
  image: assets/image/logo.png

  android_12:
    image: assets/image/logo.png
    icon_background_color: "#ffffff"
  web: false