// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'bus_locations_model.mapper.dart';

@MappableClass()
class BusLocationsModel with BusLocationsModelMappable {
  final String? id;
  @MappableField(key: 'bus_id')
  final String busId;
  final String latitude;
  final String longitude;
  final DateTime? timestamp;

  BusLocationsModel({
    required this.id,
    required this.busId,
    required this.latitude,
    required this.longitude,
    required this.timestamp,
  });
}
