// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'trips_model.mapper.dart';

@MappableClass()
class TripsModel with TripsModelMappable {
  final String? id;
  @MappableField(key: 'bus_id')
  final String busId;
  @MappableField(key: 'driver_id')
  final String driverId;
  @MappableField(key: 'trip_type')
  final bool tripType;
  @MappableField(key: 'scheduled_time')
  final DateTime? scheduledTime;
  final String? status;

  TripsModel( {
   required this.id,required this.busId,required this.driverId, required this.tripType,required this.scheduledTime,required this.status,
    
  });
}
