// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'user_model.mapper.dart';

@MappableClass()
class UserModel with UserModelMappable {
  final String name;
  final String email;
  final String phone;
  final String role;
  final String? id;
  @MappableField(key: 'image_url')
  final String? imageUrl;

  @MappableField(key: 'created_at')
  final DateTime? createdAt;
  final double? latitude;
  final double? longitude;

  UserModel({
    required this.name,
    required this.email,
    required this.phone,
    required this.role,
    this.id,
    this.imageUrl,
    this.createdAt,
    this.latitude,
    this.longitude,
  });
}
