// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'students_models.mapper.dart';

@MappableClass()
class StudentsModels with StudentsModelsMappable {
  final String? id;
  final String name;
  @MappableField(key: 'parent_id')
  final String parentId;
  final bool status;
  @MappableField(key: 'created_at')
  final DateTime? createdAt;

  StudentsModels({
    required this.id,
    required this.name,
    required this.parentId,
    required this.status,
    this.createdAt,
  });
}
