// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'students_models.mapper.dart';

@MappableClass()
class StudentsModel with StudentsModelMappable {
  final String? id;
  final String name;
  @MappableField(key: 'parent_id')
  final String parentId;
  final bool status;
  @MappableField(key: 'created_at')
  final DateTime? createdAt;
  @MappableField(key: 'driver_id')
  final String driverId;
  final String? gender;
  StudentsModel({
    required this.id,
    required this.name,
    required this.parentId,
    required this.status,
    this.createdAt,
   required this.driverId,
   this.gender
  });
}
