// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'buses_model.mapper.dart';

@MappableClass()
class BusesModel with BusesModelMappable {
  final String? id;
  @MappableField(key: 'plate_number')
  final String plateNumber;
  final int capacity;
  //String
  @MappableField(key: 'driver_id')
  final String driverId;
  @MappableField(key: 'bus_number')
  final int busNumber;
  final String model;

  @MappableField(key: 'bus_name')
  final String busName;

  BusesModel({
    required this.id,
    required this.plateNumber,
    required this.capacity,
    required this.driverId,
    required this.busName,
    required this.busNumber,
    required this.model,
  });
}
