// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'notifications_model.mapper.dart';

@MappableClass()
class NotificationsModel with NotificationsModelMappable {
  final String? id;
  @MappableField(key: 'user_id')
  final String userId;
  final String message;
  @MappableField(key: 'is_read')
  final bool isRead;
  @MappableField(key: 'created_at')
  final DateTime? createdAt;

  NotificationsModel({
      this.id,
    required this.userId,
    required this.isRead,
    required this.message,
      this.createdAt,
  });
}
