// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'trip_stop_model.mapper.dart';

@MappableClass()
class TripStopModel with TripStopModelMappable {
  final String? id;
  //student_id
  @MappableField(key: 'trip_id')
  final String tripId;
  @MappableField(key: 'student_id')
  final String studentId;
  @MappableField(key: 'stop_order')
  final int stopOrder;
  final double latitude;
  final double? longitude;
  @MappableField(key: 'address_description')
  final String? addressDescription;
  @MappableField(key: 'stop_type')
  final String? stopType;

  TripStopModel({
    required this.stopOrder,
    required this.tripId,
      this.id,
    required this.studentId,
    required this.stopType,
    required this.longitude,
    required this.latitude,
    required this.addressDescription,
  });
}
