// This file is "model.dart"
import 'package:dart_mappable/dart_mappable.dart';

// Will be generated by dart_mappable
part 'trip_model.mapper.dart';

@MappableClass()
class TripModel with TripModelMappable {
  final String? id;
  @MappableField(key: 'bus_id')
  final String busId;
  @MappableField(key: 'driver_id')
  final String driverId;
  @MappableField(key: 'trip_type')
  final String? tripType;

  @MappableField(key: 'scheduled_time')
  final DateTime? scheduledTime;
  final String? status;
  TripModel({
      this.id,
    required this.busId,
    required this.driverId,
    required this.tripType,
    required this.scheduledTime,
    required this.status,
  });
}
